### PR TITLE
[Refactor #214] converted nodes to components

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by knorth55** [comment]
Hmm. I'm having a problem.
In my environment, node name does not change with `launch` file.
Can't we change the node name from `launch` in `ROS2`?

```
$ ros2 param list
/audio/audio_capture_node:
  bitrate
  channels
  depth
  device
  dst
  format
  sample_format
  sample_rate
  use_sim_time
/launch_ros_22823:
  use_sim_time

$ ros2 node list
/audio/audio_capture_node
/launch_ros_22823
```

**Comment by knorth55** [comment]
I found out that my ROS2 distro is too old, `Eloquent`.
I need to set `node-name` instead of `name`.

**Comment by knorth55** [comment]
@weeshal can you check if this PR works?

**Comment by weeshal** [comment]
@knorth55 

+1 on the change to python launch files!

I'm using eloquent as well, and I seem to be facing a similar issue with the arguments passed into `launch_ros.Node`. How would you like to go about solving this - retain the changes necessary for Eloquent or target this towards Humble? This would be difficult without version branching like you have for ros1.

**Comment by weeshal** [comment]
Some findings:
- Currently some of the namespacing across launch files is inconsistent - the `capture.launch.xml` uses `/audio` whereas the other 2 in that package have no namespace.
- The `.launch.xml` files seem to use the value set in `audio_capture_node.cpp` field to name the node whereas the `.launch.py` files use the `node_name`(eloquent)/ `name`(later) field provided in the launch file. That should be kept consistent (you can decide whether that is suffixed with `_node` or not, as maintainer)
- Default value for audio filename is `output.mp3` but default format is `wave`. The audio file plays fine, but could be kept consistent. 
- I am unable to save/play files through the `audio_play_node`, I had this issue even before changes. If you are able to play audio, then it is some configuration error but if you are unable too, I can try to debug what might be going on.

Here is a PR with the functional changes: https://github.com/knorth55/audio_common/pull/2

**Comment by knorth55** [comment]
> Currently some of the namespacing across launch files is inconsistent - the capture.launch.xml uses /audio whereas the other 2 in that package have no namespace.

What do you mean?
All the launch files have the same namespace `/audio`.

> The .launch.xml files seem to use the value set in audio_capture_node.cpp field to name the node whereas the .launch.py files use the node_name(eloquent)/ name(later) field provided in the launch file. That should be kept consistent (you can decide whether that is suffixed with _node or not, as maintainer)

`eloquent` is EOL, we should use `name`, I think.

> Default value for audio filename is output.mp3 but default format is wave. The audio file plays fine, but could be kept consistent.

Thank you, I will fix it.

> I am unable to save/play files through the audio_play_node, I had this issue even before changes. If you are able to play audio, then it is some configuration error but if you are unable too, I can try to debug what might be going on. EDIT: looks like the messages are not being received.

You can just try running `audio_capture` and `audio_play` on one laptop with microphone and speaker.
You can hear the sound from microphone.
I recommend to use earphones because speaker causes howling.

**Comment by weeshal** [comment]
I mean the `capture_wave.launch.xml` does not have the arguments as the other 2 launch files. So it does not publish to `/audio/audio` as intended.

sounds good regarding not supporting eloquent.

and I tried both nodes with headphones and verified that messages don’t seem to be coming through (subscriber callback is not being called even when capture node is publishing). This seems out of scope for this PR though.

**Comment by knorth55** [comment]
> I mean the capture_wave.launch.xml does not have the arguments as the other 2 launch files. So it does not publish to /audio/audio as intended.

I see, I updated.

**Comment by knorth55** [comment]
> and I tried both nodes with headphones and verified that messages don’t seem to be coming through (subscriber callback is not being called even when capture node is publishing). This seems out of scope for this PR though.

This is weird. It works in my environment, and topic is correctly published.
Can you check if the topic is correctly passed by `ros2 topic info /audio/audio`?

**Comment by weeshal** [comment]
I’m not currently at my computer, but if it works in your environment then it could be because of my running on eloquent. Either way, I’m not using the audio play node

**Comment by knorth55** [comment]
OK, so can you review this PR?

**Review by weeshal — APPROVED** [review]
Looks good to me!

**Comment by knorth55** [comment]
@weeshal thank you for your help!

**Comment by weeshal** [comment]
@knorth55 thanks for the prompt review and collaboration! 😄

**Pull request merged**
