### PR TITLE
Converted nodes to components

### LINKED ISSUE #209: Convert rclcpp nodes into components
Feature Request:

Convert the audio_capture and audio_play nodes into [rclcpp components](https://docs.ros2.org/latest/api/rclcpp_components/). The benefits this would have, while still maintaining backwards compatibility (non-functional change) are:

1. Allow for [intra-process communication](https://docs.ros.org/en/foxy/Tutorials/Demos/Intra-Process-Communication.html) when nodes are running in the same component container - removing the copy overhead between publishers and subscribers in the same container (think capture and play running the same container with less latency - especially important for relatively heavy audio msg)
2. Allow for the nodes to be [loaded/unloaded dynamically.](https://docs.ros.org/en/foxy/Tutorials/Intermediate/Composition.html) For my current use-case, we want to record audio files for n seconds, instead of using a separate node to capture /audio and save to a wav file, we can utilize the already implemented gstreamer pipeline in this package to run the node for n seconds and save a wav file in this manner.

@knorth55 let me know if this is something you would be interested in - I can make the change, test and submit a PR if so!

### PR DESCRIPTION
**Pull request by weeshal**
Made changes to audio_capture and audio_play nodes:

- Changed generation of executables to use rclcpp_components, 
- Initialize gstreamer in the constructor instead of main (which is removed)
- Additional CMake changes to support this (and cleanup)

This PR closes #209

### CODE REVIEW

**Comment by weeshal** [comment]
This change will allow the ability to load an unload these nodes (utilizing the filesink more effectively), here is an example:

1. Running the following command in a terminal will launch a generic component container.
`ros2 run rclcpp_components component_container`
1. In a second terminal, running 
`ros2 component list` will show the available containers (`/ComponentManager` by default) and
`ros2 component types` will produce the available components
image
1. `ros2 component load /ComponentManager audio_capture audio_transport::RosGstCapture -p dst:=audio4.mp3 && sleep 10 && ros2 component unload /ComponentManager 1
`
will record a 10s mp3 file. (**NOTE**: each component loaded has a unique uid - the next time you run this, you should use `ros2 component unload /ComponentManager 2`)

**Comment by weeshal** [comment]
@knorth55 would you be able to test the `audio_play` node with this change? I wasn't able to get audio playing even before this change.

**Comment by knorth55** [comment]
currently i dont have much time so i will check it later.
but i have one things i want to tell you.

this pr includes several changes which are not related to `components`.
please split these changes into other PR?
PR should be compact for the review.

for example...
do you really need to change the `audio_capture` to `audio_capture_node`?

**Comment by weeshal** [comment]
Certainly node, the convention that I have followed is naming the libraries with the project name, and the executable to project_name_node. I can maybe do project_name_libraries and project_name so that all the launch changes are removed.

**Comment by knorth55** [comment]
You don't need to change the node executable name, but I think we should keep the node name in launch file, I mean.

**Comment by knorth55** [comment]
this PR is moved to #215

**Pull request closed without merging**
