### PR TITLE
audio_play fix for reproducing livestream sound

### PR DESCRIPTION
**Pull request by quattrinili**
`audio_play` when playing a livestream sound interrupts after few seconds. The fix added a parameter to control `do-timestamp` parameter, which needs to be set to false to make the livestream audio reproduced continuously.

It has been tested with the internal microphone using
`roslaunch audio_capture capture.launch` and `roslaunch audio_play play.launch do_timestamp:=true`

### CODE REVIEW

**Comment by quattrinili** [comment]
This should probably address also the iesue #120.

**Comment by nickvaras** [comment]
Just confirming that this fixes the problem mentioned. The official audio_play package is broken and only plays streamed audio for a second. With this pr and 
`roslaunch audio_play play.launch do_timestamp:=false`
the issue is fixed.

**Comment by knorth55** [comment]
:+1: 
+1 for this PR.

**Comment by bkiefer** [comment]
Please merge this pull request, it is only adding functionality and can not break existing code, but helps in various situations.

**Comment by Pokornz** [comment]
@quattrinili Is there a scenario under which it would be desirable to set the `do-timestamp` parameter to true?

**Comment by knorth55** [comment]
@Pokornz I'm also using it with `do_timestamp:=false` usually. If everyone uses it with `false` parameter, we can change the default behavior.

**Pull request merged**
