### PR TITLE
[audio_common_msgs] Add new audio msgs

### PR DESCRIPTION
**Pull request by 708yamaguchi**
From https://github.com/ros-drivers/audio_common/issues/136
In this PR, I added new audio messages, which have more information than `AudioData.msg`

For `WaveData.msg`, I used this site as a reference.
http://soundfile.sapp.org/doc/WaveFormat/
For `CompressedAudioData.msg`, I used this site as a reference.
https://www.mp3-tech.org/programmer/frame_header.html

Each field name in these msg is the same as the rosparam in `audio_capture`.
https://github.com/ros-drivers/audio_common/blob/master/audio_capture/src/audio_capture.cpp

Here's the new msg.
This msg is a slightly modified version of the one I wrote in the above issue.

WaveData.msg:
```
Header header      # Header timestamp should be acquisition time of audio
                   # Header frame_id should be position of microphone

uint8 channels     # Number of channels
uint32 sample_rate # Sampling rate [Hz]
uint8 depth        # Number of bits per audio data

uint8[] data       # Audio data buffer
                   # WAVE format is assumed
```

CompressedAudioData.msg:
```
Header header      # Header timestamp should be acquisition time of audio
                   # Header frame_id should be position of microphone

uint8 channels     # Number of channels
uint32 sample_rate # Sampling rate [Hz]
uint32 bitrate     # Amount of audio data per second [bits/s]

string format      # Specifies the format of the audio data
                   # For example, mp3
uint8[] data       # Compressed audio buffer
```

### CODE REVIEW

**Comment by knorth55** [comment]
@708yamaguchi 
should we determine wave format by `S16LE` or `16` with depth?

**Comment by 708yamaguchi** [comment]
I think it would be easier to understand if we use the same data type as rosparam used in other cpp files (int).
https://github.com/ros-drivers/audio_common/blob/3619465dc8cf0713d2f62c9cb4ce76be911fa161/audio_capture/src/audio_capture.cpp#L29

Of cource, it is more accurate to use "S16LE" than "16".
Therefore, we may need to discuss the data type (e.g. "S16LE" or "16"), which should be common for all audio_common repositories.

**Comment by 708yamaguchi** [comment]
I use `sample_format` instead of `depth` in `WaveData.msg`, because `sample_format` is introduced to `audio_capture` at https://github.com/ros-drivers/audio_common/commit/d28aa235d734541e2d8fe363d930816823ce823b

**Comment by knorth55** [comment]
@708yamaguchi thank you for your update.
FYI:
I'm now working on adding `sampling_format` for mp3 compressed audio data in #146 .
if this PR is ok and merged, you can also add `sampling_format` in `CompressedAudioData.msg` in your PR.

**Comment by knorth55** [comment]
@708yamaguchi can you also add `sampling_format` in `CompressedAudioData.msg` ?

**Comment by 708yamaguchi** [comment]
I added `sample_format` field.
In addition, I changed msg name from `CompressedAudioData` to `Mp3Data` for clarity.

**Comment by sktometometo** [comment]
@708yamaguchi The bitrate field in Mp3Data is necessary for decoding?
[output of lamemp3enc element](https://gstreamer.freedesktop.org/documentation/lame/index.html#src) does not seem to contain bitrate information.

**Comment by 708yamaguchi** [comment]
@sktometometo 
Thank you for your advice.

> Is the bitrate field in Mp3Data necessary for decoding?

I think you are right.
Bitrate is not necessary for decoding audio data. Also, channels or sample rate information is also not necessary.
For example in [audio_play.cpp](https://github.com/ros-drivers/audio_common/blob/master/audio_play/src/audio_play.cpp), mp3 data is decoded by [decodebin](https://gstreamer.freedesktop.org/documentation/playback/decodebin.html?gi-language=c) element without specifying the audio information such as bitrate, channels or sample rate

I think the audio information will help us when we process audio data, such as fourier transform or voice recognition.
If you think bitrate is not necessary for audio processing, I will remove the bitrate field from MP3Data.msg definition.
Also, if you have any good ideas on what information to add to msg, please let me know.

Thanks,

**Comment by sktometometo** [comment]
@708yamaguchi actually each mp3 frames in Mp3Data.msg has bitrate information in its frame header. http://mpgedit.org/mpgedit/mpeg_format/MP3Format.html
So I think it is redundant that ROS message has the bitrate field.

**Comment by sktometometo** [comment]
I think it is useful for compatibility with current version to split bitstream (data field) and meta information (ex. sampling rate, width) like below.
I would like to discuss about pros and cons of these splited messages and the united message ( this PR ).
Maybe it should be discussed in some issue.

AudioData.msg
```
uint8[] data
```

AudioInfo.msg
```
uint8 channels
uint32 sampling_rate
uint16 width
uint16 compression_algorithm
```

**Comment by knorth55** [comment]
I rethink the idea, and `AudioInfo.msg` is a good solution for backward compatibility.

**Comment by 708yamaguchi** [comment]
I think `AudioInfo.msg` is a good idea, too.

My only concern is that we may need to add header to `AudioData.msg` to synchronize these messages.
The header addition breaks backward compatibility.

**Comment by knorth55** [comment]
`header` is not needed for synchronization i.e. `message_filters` when we set `use_header=false`.
also `audio_info` is only require one time probably.

but I think that `header` should be included in `audio` topic, too.
But I also think we should avoid changing existing message type.
So my solution is leave `AudioData.msg` as it is and add `AudioInfo.msg` as meta data message.

**Comment by 708yamaguchi** [comment]
Thank you very much for your repeated advice.
I created pull request to add `AudioInfo.msg` at https://github.com/ros-drivers/audio_common/pull/152, so I close this pull request.

**Pull request closed without merging**
