### PR TITLE
Add is_speeching node for checking robot is speaking

### PR DESCRIPTION
**Pull request by iory**
Added is_speeching node to output the bool value of whether the robot is speaking.

### CODE REVIEW

**Comment by knorth55** [comment]
speech is a noun, so can you change to `speaking`?
Except that, this PR looks good to me.

**Comment by iory** [comment]
Thanks!
I modified the name.

**Comment by knorth55** [comment]
can you update `CMakeLists.txt`?
https://github.com/ros-drivers/audio_common/blob/master/sound_play/CMakeLists.txt#L19-L27

**Comment by iory** [comment]
Thanks. Updated. https://github.com/ros-drivers/audio_common/pull/176/commits/307387ca0018f3e939af0711435294341ce51b6b

**Review by knorth55 — APPROVED** [review]

**Comment by peci1** [comment]
Hi, I've stumbled upon this PR in the release notes. Thank you for providing it, but the implementation doesn't seem right to me.

1. `robotsound` topic published by soundplay_node.py is of type `sound_play/SoundRequest`, but this node subscribes type `GoalStatusArray`. Is it meant to subscribe to topic `sound_play/status` instead?
2. The instance of rospy.Timer created in constructor is not saved to any variable. I really wonder this works. 
3. The same with the instance of `IsSpeaking` in the `__main__` part. Usually, an object is destroyed as soon as it is not referenced from anywhere. I guess the fact that it works is pretty fragile.
4. There are two ways to instruct the soundplay node to speak - the action server, and the `robotsound` topic. This node only handles the action server part.
5. Wouldn't it be better to examine the `status` field of the action status messages instead of `text`? I guess `status` should be more precise.

**Comment by knorth55** [comment]
> 2. The instance of rospy.Timer created in constructor is not saved to any variable. I really wonder this works.

> 3. The same with the instance of IsSpeaking in the __main__ part. Usually, an object is destroyed as soon as it is not referenced from anywhere. I guess the fact that it works is pretty fragile.

In terms of garbage collection, the instance should be set to prevent the garbage collection.
However, I'm not sure but it is thread object and running, so garbage collector does not destroy the object, I think.
But, for the clarification, it should be set as object like `self.timer` and `app`.
(Also, I feel a bit nervous to see this kind of code running...)

> 1. robotsound topic published by soundplay_node.py is of type sound_play/SoundRequest, but this node subscribes type GoalStatusArray. Is it meant to subscribe to topic sound_play/status instead?

> 4. There are two ways to instruct the soundplay node to speak - the action server, and the robotsound topic. This node only handles the action server part.

Yes, you are right. We only consider the usecase of action, not topic one.

> 5. Wouldn't it be better to examine the status field of the action status messages instead of text? I guess status should be more precise.

This is a good suggestion! @iory How do you think?

**Comment by knorth55** [comment]
@iory ping

**Pull request merged**
