### PR TITLE
[audio_common_msgs] add AudioDataStamped.msg

### PR DESCRIPTION
**Pull request by knorth55**
related to #201 
I add `AudioDataStamped` msg, which has `Header`.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Should `AudioInfo` fileld be added to `AudioDataStamped` msg?
https://github.com/ros-drivers/audio_common/blob/master/audio_common_msgs/msg/AudioInfo.msg

**Comment by knorth55** [comment]
Hmm, we need discussion about it.
IMO, `AudioInfo` is not required to be published in high frequency as `CameraInfo`.
But, I understand all information should be in one message, which is easier for users.

**Comment by v4hn** [comment]
I agree with @knorth55 . `CameraInfo` can basically adapt parameters to changes in focal length or different modes of the camera. For `AudioInfo` the main use cases would be
1. changing number of channels
  - The only use-case where I might see that is for sound source separation with a previously unknown number of sources. I'm not convinced this use-case is worth adding the overhead everywhere.
2.  variable bit-rate (VBR), but that's already represented in MP3 if used and `bitrate` would be redundant
3. `image_transport`-style transparent transport switching (pcm-mp3-ogg). I believe if someone wants that, they would implement `audio_transport` instead.

I very much prefer to only look at `AudioInfo` once on startup and verify/setup the subscriber accordingly.

**Review by v4hn — APPROVED** [review]
Needs to be implemented in `audio_capture`/play of course. :-)

**Comment by 708yamaguchi** [comment]
@v4hn
Thank you for your insights.
I agree with your idea.

**Comment by v4hn** [comment]
Great, thanks.
Now somebody just has to implement a proper time reading from libgstreamer in `audio_capture`.
Until then even the `seq` number in the header can already help detect dropped packages due to ROS (however not due to the gstreamer pipeline!). :)
Assuming you want to publish `audio_stamped` in addition to `audio` from there now.

**Comment by knorth55** [comment]
> Now somebody just has to implement a proper time reading from libgstreamer in audio_capture.

I think the first implemtation is like you did in [`master...v4hn:audio_common:master-audio-stamped`#diff-9a3a6c75b5](https://github.com/ros-drivers/audio_common/compare/master...v4hn:audio_common:master-audio-stamped#diff-9a3a6c75b5666c38b65ede971b37b77fc1ebdeb2706e27041e0ff2a103391b0aR178).
I need to find the better way, but I don't have enough time now.

> Assuming you want to publish audio_stamped in addition to audio from there now.

Yes :)

**Pull request merged**
