### PR TITLE
[sound_play/scripts/soundplay_node.py] refactor code

### PR DESCRIPTION
**Pull request by furushchev**
from https://github.com/ros-drivers/audio_common/pull/77
In this pull request I only refactored code and remove unnecessary while loop.

### CODE REVIEW

**Comment by furushchev** [comment]
friendly ping @trainman419

**Comment by furushchev** [comment]
@trainman419 any update?

**Comment by trainman419** [comment]
I'm waiting on #78 before I consider merging this.

**Comment by trainman419** [comment]
This has conflicts and is generally out of date. Closing.

Please consider retargeting this to the `master` branch and include unit tests or some other test results that demonstrate that it does not break existing behavior.

**Pull request closed without merging**
