### PR TITLE
Fix for audio_play to continue playing and port to gstreamer 1.0

### PR DESCRIPTION
**Pull request by BennyRe**
This fixes issue #50.
When the data stream on /audio stops the gstreamer pipeline is set to the 'pause' state. As soon as data arrives again the pipeline is set back to 'playing'.

As a first attempt to fix this issue I ported the audio_play and audio_capture packages to gstreamer 1.0 because 0.10 is deprecated but the issue remained.

This is the first time I put my hand on gstreamer so please correct me if I'm doing something wrong here.

Now against the master branch.

### CODE REVIEW

**Comment by trainman419** [comment]
Same comments here as on #54 ; please update the `need-data` message to be a warning.

**Comment by jack-oquin** [comment]
The new dependency on ``libgstreamer1.0-dev`` seems to work on Trusty, Utopic, Vivid and Wily, so the updated version could be released to Jade.

For Indigo, we would require Saucy support as well. Since Saucy is no longer actively supported by Ubuntu, it is [unclear whether that version or some other is available](http://packages.ubuntu.com/trusty/libgstreamer1.0-dev). Does anybody know for sure?

Instead of making breaking changes that will no longer work with older releases, I wonder if we would be better off providing a generic gstreamer dependency, then handling the different versions with CMake tests and conditional compilation in the code.

**Comment by trainman419** [comment]
Yes; libgstreamer1.0-dev is/was in Saucy: http://old-releases.ubuntu.com/ubuntu/dists/saucy/main/binary-amd64/Packages.bz2

That said, adding dependencies to a released package is generally cause for trouble, because apt will only install a package with new dependencies during a dist-upgrade (not during upgrade). Combining that with changing the package ABI in the same update will result in new packages built on the farm against the new ABI. Since we can't force downstream packages to depend on a specific version of audio_common, apt may upgrade downstream packages without upgrading the package they depend on, resulting in ABI breakage.

I like upgrading to a more stable version of gstreamer, but I will hold the upgrade for the next version of ROS.

**Comment by jack-oquin** [comment]
Makes sense to me.

**Pull request merged**
