### PR TITLE
get capture audio stamp from gstreamer in real recording

### PR DESCRIPTION
**Pull request by v4hn**
This implementation works well for me and does not change behavior when combined with a simulator.

### CODE REVIEW

**Comment by knorth55** [comment]
I learnt a bit about gstreamer clocking now.
https://gstreamer.freedesktop.org/documentation/application-development/advanced/clocks.html?gi-language=c
https://gstreamer.freedesktop.org/documentation/gstreamer/gstbuffer.html?gi-language=c

`base-time`: The timestamp when the the pipleline state goes into `PLAYING` state (Absolute time)
`pts`: The timestamp when the buffer should be presented to user (Relative time from `base-time`)
So the timestamp should be `base-time + pts`, and this PR calculates that.

**Comment by v4hn** [comment]
yeah, the gstreamer documentation is excessive, but also hard to parse... Took me some time to figure out the API and I eventually found a very recent almost-correct stackoverflow post (which I fail to find again right now).

**Comment by knorth55** [comment]
Gstreamer is made by genius and also for genius, that is why the documentation is huge but hard to learn whole part.
Anyway, I will check this PR on my laptop and merge this.

**Comment by knorth55** [comment]
@v4hn thank you for your contribution!

**Pull request merged**
